# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Deleting model 'ELFDataRequestImpressionClick'
        db.delete_table(u'spendata_elfdatarequestimpressionclick')

        # Adding model 'ELFClickData'
        db.create_table(u'spendata_elfclickdata', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('event_time', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('transaction_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('transaction_time', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('user_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_id_new', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('publisher_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('site_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_unit_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_unit_grp_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('ad_width', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_height', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('page_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('delivery_medium_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('site_section_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('content_type_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('content_topic_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('screen_location_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('advertiser_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('order_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('line_item_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('is_companion', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_auto_refresh', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_fallback_ad', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_pre_fetch', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('user_ip_address', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_latitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('user_longitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('user_continent', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_country', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_state', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_dma', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_msa', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_city', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_zip', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('user_connection_speed', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_connection_type', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_device', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('mobile_carrier', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('mobile_net_type', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_screen_res', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_agent', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_name', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_version', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_operating_system', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_os_version', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_language', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('page_url', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('referrer_url', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('matched_targeting', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('custom_fields', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('audience_segments', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('traffic_rejected', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('serial_number', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('part_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('revision', self.gf('django.db.models.fields.IntegerField')(default=1)),
        ))
        db.send_create_signal(u'spendata', ['ELFClickData'])

        # Adding model 'ELFImpressionData'
        db.create_table(u'spendata_elfimpressiondata', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('event_time', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('transaction_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('transaction_time', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('user_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_id_new', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('publisher_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('site_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_unit_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_unit_grp_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('ad_width', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_height', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('page_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('delivery_medium_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('site_section_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('content_type_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('content_topic_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('screen_location_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('advertiser_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('order_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('line_item_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('is_companion', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_auto_refresh', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_fallback_ad', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_pre_fetch', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('user_ip_address', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_latitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('user_longitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('user_continent', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_country', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_state', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_dma', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_msa', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_city', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_zip', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('user_connection_speed', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_connection_type', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_device', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('mobile_carrier', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('mobile_net_type', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_screen_res', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_agent', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_name', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_version', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_operating_system', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_os_version', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_language', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('page_url', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('referrer_url', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('matched_targeting', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('custom_fields', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('audience_segments', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('traffic_rejected', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('serial_number', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('part_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('revision', self.gf('django.db.models.fields.IntegerField')(default=1)),
        ))
        db.send_create_signal(u'spendata', ['ELFImpressionData'])

        # Adding model 'ELFRequestData'
        db.create_table(u'spendata_elfrequestdata', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('event_time', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('transaction_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('transaction_time', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('user_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_id_new', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('publisher_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('site_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_unit_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_unit_grp_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('ad_width', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_height', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('page_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('delivery_medium_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('site_section_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('content_type_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('content_topic_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('screen_location_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('advertiser_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('order_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('line_item_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('is_companion', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_auto_refresh', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_fallback_ad', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('is_pre_fetch', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('user_ip_address', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_latitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('user_longitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('user_continent', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_country', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_state', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_dma', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_msa', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_city', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_zip', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('user_connection_speed', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_connection_type', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_device', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('mobile_carrier', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('mobile_net_type', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_screen_res', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_agent', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_name', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_version', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_operating_system', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_os_version', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_language', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('page_url', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('referrer_url', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('matched_targeting', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('custom_fields', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('audience_segments', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('traffic_rejected', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('serial_number', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('part_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('revision', self.gf('django.db.models.fields.IntegerField')(default=1)),
        ))
        db.send_create_signal(u'spendata', ['ELFRequestData'])


    def backwards(self, orm):
        # Adding model 'ELFDataRequestImpressionClick'
        db.create_table(u'spendata_elfdatarequestimpressionclick', (
            ('user_latitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('user_os_version', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('transaction_time', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('traffic_rejected', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('ad_unit_grp_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('screen_location_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('content_topic_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('event_time', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('user_state', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('is_companion', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('user_screen_res', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_language', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('publisher_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('transaction_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_zip', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('user_connection_type', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('advertiser_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('user_longitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('content_type_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('mobile_carrier', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_country', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('matched_targeting', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('referrer_url', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('page_url', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_device', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('site_section_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('event_type', self.gf('django.db.models.fields.CharField')(default='R', max_length=1, blank=True)),
            ('mobile_net_type', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('site_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('is_fallback_ad', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('user_dma', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_version', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('browser_name', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('page_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('line_item_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('custom_fields', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_connection_speed', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_msa', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_ip_address', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('is_auto_refresh', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('ad_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('order_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('is_pre_fetch', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('ad_height', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('user_city', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('audience_segments', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('delivery_medium_id', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_operating_system', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('ad_width', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ad_unit_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('user_agent', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_continent', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('user_id_new', self.gf('django.db.models.fields.BooleanField')(default=False)),
        ))
        db.send_create_signal(u'spendata', ['ELFDataRequestImpressionClick'])

        # Deleting model 'ELFClickData'
        db.delete_table(u'spendata_elfclickdata')

        # Deleting model 'ELFImpressionData'
        db.delete_table(u'spendata_elfimpressiondata')

        # Deleting model 'ELFRequestData'
        db.delete_table(u'spendata_elfrequestdata')


    models = {
        u'spendata.acxiomdata': {
            'Meta': {'object_name': 'AcxiomData'},
            'business_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'city_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'corporate_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'display_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'post_directional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'state_code': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'street_directional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'street_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'street_number': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'street_suffix': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unit_designator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unit_number': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zip_code': ('django.db.models.fields.TextField', [], {'null': 'True'})
        },
        u'spendata.elfclickdata': {
            'Meta': {'object_name': 'ELFClickData'},
            'ad_height': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_unit_grp_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ad_unit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_width': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'advertiser_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'audience_segments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_language': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_topic_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'custom_fields': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'event_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_auto_refresh': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_companion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_fallback_ad': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_pre_fetch': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'line_item_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'matched_targeting': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_net_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'part_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'publisher_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'referrer_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'revision': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'screen_location_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_section_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'traffic_rejected': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transaction_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_agent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_continent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_device': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_dma': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id_new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_ip_address': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_operating_system': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_os_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_screen_res': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfdataconversion': {
            'Meta': {'object_name': 'ELFDataConversion'},
            'action_type': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ad_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_unit_grp_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ad_unit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'audience_segments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'beacon_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'browser_language': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'custom_fields': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'event_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_click': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'line_item_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'mobile_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_net_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'page_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'referrer_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'traffic_rejected': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transaction_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_agent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_continent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_device': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_dma': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id_new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_ip_address': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_operating_system': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_os_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfimpressiondata': {
            'Meta': {'object_name': 'ELFImpressionData'},
            'ad_height': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_unit_grp_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ad_unit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_width': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'advertiser_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'audience_segments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_language': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_topic_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'custom_fields': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'event_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_auto_refresh': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_companion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_fallback_ad': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_pre_fetch': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'line_item_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'matched_targeting': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_net_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'part_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'publisher_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'referrer_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'revision': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'screen_location_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_section_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'traffic_rejected': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transaction_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_agent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_continent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_device': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_dma': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id_new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_ip_address': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_operating_system': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_os_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_screen_res': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfrequestdata': {
            'Meta': {'object_name': 'ELFRequestData'},
            'ad_height': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_unit_grp_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ad_unit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_width': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'advertiser_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'audience_segments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_language': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_topic_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'custom_fields': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'event_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_auto_refresh': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_companion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_fallback_ad': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_pre_fetch': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'line_item_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'matched_targeting': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_net_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'part_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'publisher_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'referrer_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'revision': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'screen_location_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_section_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'traffic_rejected': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transaction_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_agent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_continent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_device': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_dma': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id_new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_ip_address': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_operating_system': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_os_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_screen_res': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfserial': {
            'Meta': {'object_name': 'ELFSerial'},
            'created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'serial': ('django.db.models.fields.BigIntegerField', [], {'default': '0', 'null': 'True', 'blank': 'True'})
        },
        u'spendata.mobileapplocationdata': {
            'Meta': {'object_name': 'MobileAppLocationData'},
            'capture_time_utc': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'device_data': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'location_data'", 'null': 'True', 'to': u"orm['spendata.MobileAppMobileData']"}),
            'device_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.mobileappmobiledata': {
            'Meta': {'object_name': 'MobileAppMobileData'},
            'device_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'device_manufacturer': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'device_model': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user_data': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'mobile_data'", 'null': 'True', 'to': u"orm['spendata.MobileAppUserData']"}),
            'user_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'wireless_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.mobileappuserdata': {
            'Meta': {'object_name': 'MobileAppUserData'},
            'age_range': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'area_code': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'first_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'gender': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'income_range': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'last_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_number': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_email': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxaccount': {
            'Meta': {'object_name': 'OpenXAccount'},
            'ac_account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'account_manager_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'account_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'allow_unbranded_buyers': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'billing_contact_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'blocked_adcategories': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_contentattributes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_creativetypes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_languages': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brand_labels': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brands': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'buyer_breakout': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'clicks': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'country_of_business_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'currency_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'domains': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'exchange': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fill_rate': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'filters': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'instance_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'market_active': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'market_currency_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primary_contact_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'requests': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sales_lead_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'single_ad_limitation': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'timezone_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'total_conversions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'total_impressions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'uplift': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxad': {
            'Meta': {'object_name': 'OpenXAd'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_weight': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '3', 'decimal_places': '1', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'creative_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'days_of_week': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deliver_by_default': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'hours_of_day': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'individual_display_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lineitem_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'session_display_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'session_duration': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxadunit': {
            'Meta': {'object_name': 'OpenXAdunit'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'alt_sizes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_topics': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primary_size': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'real_time_bid_floor': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '9', 'decimal_places': '2', 'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sitesection_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'vast_tag': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxadunitgroup': {
            'Meta': {'object_name': 'OpenXAdunitgroup'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'adunits': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'masteradunit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'vast_tag': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxcreative': {
            'Meta': {'object_name': 'OpenXCreative'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'bitrate': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '2', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'duration': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '2', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'file': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'file2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'file_size': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '11', 'decimal_places': '2', 'blank': 'True'}),
            'height': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mime_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'orig_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'source': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'uri': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'width': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxlineitem': {
            'Meta': {'object_name': 'OpenXLineitem'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_delivery_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'budget_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'buying_model_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'companion_fill_method_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'daily_click_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'daily_impression_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'daily_impression_goal': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deliver_by_default': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'individual_display_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lifetime_action_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lifetime_click_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lifetime_impression_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lifetime_impression_goal': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'make_good': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'oxtl': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'pacing_model_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'pricing_model_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'pricing_rate': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '11', 'decimal_places': '4', 'blank': 'True'}),
            'priority': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'session_display_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'session_duration': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'share_of_voice': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '3', 'decimal_places': '1', 'blank': 'True'}),
            'single_ad_limitation': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'targeting_rules': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxorder': {
            'Meta': {'object_name': 'OpenXOrder'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'booking_account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'budget': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '11', 'decimal_places': '2', 'blank': 'True'}),
            'click_through_window': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'creator_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primary_analyst_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'primary_trafficker_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sales_lead_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'secondary_trafficker_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'single_ad_limitation': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'view_through_window': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxreport': {
            'Meta': {'object_name': 'OpenXReport'},
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'parameter_string': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'relative_date': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxrole': {
            'Meta': {'object_name': 'OpenXRole'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'acl_uid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'compiled_acl': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'system': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxrule': {
            'Meta': {'object_name': 'OpenXRule'},
            'attribute': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'dimension': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lineitem_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'operator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'value': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxsite': {
            'Meta': {'object_name': 'OpenXSite'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'allow_unbranded_buyers': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'blocked_adcategories': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_contentattributes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_creativetypes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_languages': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brand_labels': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brands': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'category_override': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'content_topic_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'domain_override': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'domains': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'filters': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'platform_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'url': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxuser': {
            'Meta': {'object_name': 'OpenXUser'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'default_report_range': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'email': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'first_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'last_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'locale': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'roles': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'terms_accepted': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'verified': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        }
    }

    complete_apps = ['spendata']