# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'OpenXAdTargetingIndexCity'
        db.create_table(u'spendata_openxadtargetingindexcity', (
            ('city', self.gf('django.db.models.fields.TextField')(primary_key=True)),
        ))
        db.send_create_signal(u'spendata', ['OpenXAdTargetingIndexCity'])

        # Adding model 'OpenXAdTargetingIndexBusinessName'
        db.create_table(u'spendata_openxadtargetingindexbusinessname', (
            ('business_name', self.gf('django.db.models.fields.TextField')(primary_key=True)),
        ))
        db.send_create_signal(u'spendata', ['OpenXAdTargetingIndexBusinessName'])


    def backwards(self, orm):
        # Deleting model 'OpenXAdTargetingIndexCity'
        db.delete_table(u'spendata_openxadtargetingindexcity')

        # Deleting model 'OpenXAdTargetingIndexBusinessName'
        db.delete_table(u'spendata_openxadtargetingindexbusinessname')


    models = {
        u'spendata.acxiombdfgroups': {
            'Meta': {'object_name': 'AcxiomBdfGroups'},
            'addressprivacyflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'addresstypeindicator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ageofrecord': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bcsflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'booknumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'businessflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'businessname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'captioncounter': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'captionparentflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'captionsequencenumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cbsa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'chainid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'changecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cityname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contactfirstname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contactgender': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contactlastname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contacttitle': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'deliverabilityindicator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'directorypage': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'employeesize': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ethnicownedbusiness': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fax': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'filemaintenanceflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fips': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fulladdress': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'masterrecordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'phone': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'phonecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'postdirectional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'precisioncode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primarybusinessclassificationflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'pubdate': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'rbocunique': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'recordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'recordnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'salesvolume': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'secondphonenumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'secondphonenumbercode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sectionnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sohoflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'solicitationrestrictions': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'statecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetdirectional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetsuffix': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transactioncreatedate': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unitdesignator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unitnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'vanitycityname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'verificationflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'webaddress': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'womenownedbusiness': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zip4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zipcode': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.acxiombdfindex': {
            'Meta': {'object_name': 'AcxiomBdfIndex'},
            'ebdfflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'groupflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'masterrecordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'oneperflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'oneperid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'orgflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'recordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'})
        },
        u'spendata.acxiombdforgs': {
            'Meta': {'object_name': 'AcxiomBdfOrgs'},
            'addressprivacyflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'addresstypeindicator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ageofrecord': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bcsflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'booknumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'businessflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'businessname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'captioncounter': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'captionparentflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'captionsequencenumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cbsa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'chainid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'changecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cityname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contactfirstname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contactgender': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contactlastname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contacttitle': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'deliverabilityindicator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'directorypage': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'employeesize': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ethnicownedbusiness': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fax': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'filemaintenanceflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fips': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fulladdress': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'masterrecordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'phone': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'phonecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'postdirectional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'precisioncode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primarybusinessclassificationflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'pubdate': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'rbocunique': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'recordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'recordnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'salesvolume': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'secondphonenumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'secondphonenumbercode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sectionnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sohoflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'solicitationrestrictions': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'statecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetdirectional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetsuffix': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transactioncreatedate': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unitdesignator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unitnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'vanitycityname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'verificationflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'webaddress': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'womenownedbusiness': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zip4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zipcode': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.acxiombdfprimary': {
            'Meta': {'object_name': 'AcxiomBdfPrimary'},
            'addressprivacyflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'addresstypeindicator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ageofrecord': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bcsflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'booknumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'businessflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'businessname': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'caption1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'caption6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'captioncounter': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'captionparentflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'captionsequencenumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cbsa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'chainid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'changecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cityname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contactfirstname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contactgender': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contactlastname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'contacttitle': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'deliverabilityindicator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'directorypage': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'employeesize': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ethnicownedbusiness': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fax': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'filemaintenanceflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fips': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fulladdress': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'masterrecordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'openx_account_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'null': 'True', 'blank': 'True'}),
            'phone': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'phonecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'postdirectional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'precisioncode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primarybusinessclassificationflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'pubdate': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'rbocunique': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'recordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'recordnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'salesvolume': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'secondphonenumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'secondphonenumbercode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sectionnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sohoflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'solicitationrestrictions': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'statecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetdirectional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetsuffix': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transactioncreatedate': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unitdesignator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unitnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'vanitycityname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'verificationflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'webaddress': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'womenownedbusiness': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zip4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zipcode': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.acxiombdfprimarybusinessname': {
            'Meta': {'object_name': 'AcxiomBdfPrimaryBusinessName'},
            'businessname': ('django.db.models.fields.TextField', [], {'primary_key': 'True'})
        },
        u'spendata.acxiomdata': {
            'Meta': {'object_name': 'AcxiomData'},
            'business_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'city_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'corporate_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'display_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'post_directional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'state_code': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'street_directional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'street_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'street_number': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'street_suffix': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unit_designator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unit_number': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zip_code': ('django.db.models.fields.TextField', [], {'null': 'True'})
        },
        u'spendata.acxiomebdford': {
            'Meta': {'object_name': 'AcxiomEbdfOrd'},
            'addressprivacyflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'adsize': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'adtype': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'adultcontentflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ageofrecord': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'associations': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'associationssynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'bdc6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brands': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brandssynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'businesslink': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'businessname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cbsa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'certifications': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'certificationssynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'chainid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cityname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'corporatename': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'creditcardsaccepted': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'deliverycode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'directions': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'directorynumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'discountcode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'displayname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'emailaddress': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fax': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'freecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'generalcontent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'generalcontentsynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'groupsserved': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'groupsservedsynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'hours': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'industrytype': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'industrytypesynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'language': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'locationfeatures': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'locationfeaturessynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mailsuppression': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'masterrecordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'modelsfield': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'modelssynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'naics6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'nosolicitation': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'orderingmethods': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'orderingmethodssynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'paymentmode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'paymentmodesynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'phone': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'phonecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'phonesuppression': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'postdirectional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primarybusinessclassificationflag': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'productfeatures': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'productfeaturessynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'products': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'productssynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'professionalsonstaff': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'professionalsonstaffsynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'programsoffered': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'programsofferedsynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'pubdate': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'recordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'secondphonenumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'secondphonenumbercode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'servicearea': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'servicefeatures': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'servicefeaturessynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'services': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'servicessynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sic6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'slogans': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'specialconsiderations': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'specialconsiderationssynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'specialhours': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'specialhourssynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'specialties': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'specialtiessynonyms': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'statecode': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetdirectional': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetname': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'streetsuffix': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph5': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'syph6': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'trademark': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unitdesignator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'unitnumber': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'webaddress': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'yearsinbus': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'yearstarted': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zip4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'zipcode': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.advertiserstores': {
            'Meta': {'object_name': 'AdvertiserStores'},
            'acxiom_masterrecordid': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'acxiom_recordid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'openx_account_id': ('django.db.models.fields.TextField', [], {'db_index': 'True'})
        },
        u'spendata.elfclickdata': {
            'Meta': {'object_name': 'ELFClickData'},
            'ad_height': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True', 'null': 'True', 'blank': 'True'}),
            'ad_unit_grp_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ad_unit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_width': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'advertiser_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True', 'null': 'True', 'blank': 'True'}),
            'audience_segments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_language': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_topic_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'custom_fields': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'event_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_auto_refresh': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_companion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_fallback_ad': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_pre_fetch': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'line_item_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'matched_targeting': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_net_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'part_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'publisher_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'referrer_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'revision': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'screen_location_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_section_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'traffic_rejected': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transaction_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_agent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_continent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_device': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_dma': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'user_id_new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_ip_address': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_operating_system': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_os_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_screen_res': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfclickserial': {
            'Meta': {'object_name': 'ELFClickSerial'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfconversiondata': {
            'Meta': {'object_name': 'ELFConversionData'},
            'action_type': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ad_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True', 'null': 'True', 'blank': 'True'}),
            'ad_unit_grp_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ad_unit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'audience_segments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'beacon_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'browser_language': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'custom_fields': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'event_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_click': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'line_item_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'mobile_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_net_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'page_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'referrer_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'traffic_rejected': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transaction_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_agent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_continent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_device': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_dma': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'user_id_new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_ip_address': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_operating_system': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_os_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfconversionserial': {
            'Meta': {'object_name': 'ELFConversionSerial'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfimpressiondata': {
            'Meta': {'object_name': 'ELFImpressionData'},
            'ad_height': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True', 'null': 'True', 'blank': 'True'}),
            'ad_unit_grp_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ad_unit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_width': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'advertiser_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True', 'null': 'True', 'blank': 'True'}),
            'audience_segments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_language': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_topic_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'custom_fields': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'event_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_auto_refresh': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_companion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_fallback_ad': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_pre_fetch': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'line_item_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'matched_targeting': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_net_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'part_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'publisher_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'referrer_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'revision': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'screen_location_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_section_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'traffic_rejected': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transaction_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_agent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_continent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_device': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_dma': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'user_id_new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_ip_address': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_operating_system': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_os_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_screen_res': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfimpressionserial': {
            'Meta': {'object_name': 'ELFImpressionSerial'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfrequestdata': {
            'Meta': {'object_name': 'ELFRequestData'},
            'ad_height': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True', 'null': 'True', 'blank': 'True'}),
            'ad_unit_grp_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ad_unit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_width': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'advertiser_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True', 'null': 'True', 'blank': 'True'}),
            'audience_segments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_language': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'browser_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_topic_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'custom_fields': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'event_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_auto_refresh': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_companion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_fallback_ad': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_pre_fetch': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'line_item_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'matched_targeting': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_net_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'page_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'part_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'publisher_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'referrer_url': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'revision': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'screen_location_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_section_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'traffic_rejected': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transaction_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_agent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_speed': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_connection_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_continent': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_device': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_dma': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'user_id_new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_ip_address': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_msa': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_operating_system': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_os_version': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_screen_res': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.elfrequestserial': {
            'Meta': {'object_name': 'ELFRequestSerial'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'serial_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.mobileapplocationdata': {
            'Meta': {'object_name': 'MobileAppLocationData'},
            'capture_time_utc': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'device_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.mobileappmobiledata': {
            'Meta': {'object_name': 'MobileAppMobileData'},
            'device_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'unique': 'True', 'blank': 'True'}),
            'device_manufacturer': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'device_model': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'wireless_carrier': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.mobileappuserdata': {
            'Meta': {'object_name': 'MobileAppUserData'},
            'age_range': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'area_code': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'first_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'gender': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'income_range': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'last_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'mobile_number': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'social_network_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'user_city': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_country': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_email': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'unique': 'True', 'blank': 'True'}),
            'user_state': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_zip': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.mobileappuserhomecircle': {
            'Meta': {'object_name': 'MobileAppUserHomeCircle'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'db_index': 'True', 'blank': 'True'}),
            'weighting': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxaccount': {
            'Meta': {'object_name': 'OpenXAccount'},
            'ac_account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'account_manager_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'account_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'allow_unbranded_buyers': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'billing_contact_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'blocked_adcategories': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_contentattributes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_creativetypes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_languages': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brand_labels': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brands': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'buyer_breakout': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'clicks': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'country_of_business_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'currency_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'domains': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'exchange': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'fill_rate': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'filters': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'instance_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'market_active': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'market_currency_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primary_contact_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'requests': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sales_lead_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'single_ad_limitation': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'timezone_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'total_conversions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'total_impressions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'uplift': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxad': {
            'Meta': {'object_name': 'OpenXAd'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True', 'null': 'True', 'blank': 'True'}),
            'ad_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_weight': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '3', 'decimal_places': '1', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'creative_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'days_of_week': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deliver_by_default': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'hours_of_day': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'individual_display_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lineitem_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'offer': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'offer_brief': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'session_display_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'session_duration': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxadtargetingindex': {
            'Meta': {'object_name': 'OpenXAdTargetingIndex'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True'}),
            'ad_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True'}),
            'ad_title': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'business_address': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'business_name': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'business_telephone': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'business_url': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'lineitem_id': ('django.db.models.fields.IntegerField', [], {'db_index': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'offer': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'offer_brief': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'targeting': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxadtargetingindexbusinessname': {
            'Meta': {'object_name': 'OpenXAdTargetingIndexBusinessName'},
            'business_name': ('django.db.models.fields.TextField', [], {'primary_key': 'True'})
        },
        u'spendata.openxadtargetingindexcity': {
            'Meta': {'object_name': 'OpenXAdTargetingIndexCity'},
            'city': ('django.db.models.fields.TextField', [], {'primary_key': 'True'})
        },
        u'spendata.openxadunit': {
            'Meta': {'object_name': 'OpenXAdunit'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'alt_sizes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_topics': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primary_size': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'real_time_bid_floor': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '9', 'decimal_places': '2', 'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sitesection_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'vast_tag': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxadunitgroup': {
            'Meta': {'object_name': 'OpenXAdunitgroup'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'adunits': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'masteradunit_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'site_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'vast_tag': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxcreative': {
            'Meta': {'object_name': 'OpenXCreative'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'bitrate': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '2', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'duration': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '2', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'file': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'file2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'file_size': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '11', 'decimal_places': '2', 'blank': 'True'}),
            'height': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mime_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'orig_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'source': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'uri': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'width': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxlineitem': {
            'Meta': {'object_name': 'OpenXLineitem'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ad_delivery_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'budget_type': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'buying_model_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'companion_fill_method_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'daily_click_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'daily_impression_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'daily_impression_goal': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deliver_by_default': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'individual_display_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lifetime_action_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lifetime_click_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lifetime_impression_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lifetime_impression_goal': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'make_good': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'order_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'oxtl': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'pacing_model_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'pricing_model_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'pricing_rate': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '11', 'decimal_places': '4', 'blank': 'True'}),
            'priority': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'session_display_cap': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'session_duration': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'share_of_voice': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '3', 'decimal_places': '1', 'blank': 'True'}),
            'single_ad_limitation': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'targeting_rules': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxorder': {
            'Meta': {'object_name': 'OpenXOrder'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'booking_account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'budget': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '11', 'decimal_places': '2', 'blank': 'True'}),
            'click_through_window': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'creator_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'primary_analyst_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'primary_trafficker_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sales_lead_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'secondary_trafficker_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'single_ad_limitation': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'view_through_window': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxreport': {
            'Meta': {'object_name': 'OpenXReport'},
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'parameter_string': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'relative_date': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'user_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxrole': {
            'Meta': {'object_name': 'OpenXRole'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'acl_uid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'compiled_acl': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'system': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxrule': {
            'Meta': {'object_name': 'OpenXRule'},
            'attribute': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'dimension': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lineitem_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'operator': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'value': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxsite': {
            'Meta': {'object_name': 'OpenXSite'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'allow_unbranded_buyers': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'blocked_adcategories': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_contentattributes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_creativetypes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'blocked_languages': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brand_labels': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'brands': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'category_override': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'content_topic_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'content_type_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'delivery_medium_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'domain_override': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'domains': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'filters': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'platform_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'url': ('django.db.models.fields.TextField', [], {'blank': 'True'})
        },
        u'spendata.openxuser': {
            'Meta': {'object_name': 'OpenXUser'},
            'account_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'default_report_range': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'deleted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'email': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'external_id': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'first_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'last_name': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'locale': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'modified_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'roles': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'status': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'terms_accepted': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'verified': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.openxuseremail': {
            'Meta': {'object_name': 'OpenXUserEmail'},
            'email': ('django.db.models.fields.TextField', [], {'primary_key': 'True'})
        },
        u'spendata.publishercompanydetails': {
            'Meta': {'object_name': 'PublisherCompanyDetails'},
            'address': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'city': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'company_name': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'montavo_ad_network_optin': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'owner_name': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'phone_number': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'publisherid': ('django.db.models.fields.TextField', [], {'db_index': 'True'}),
            'state': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'zipcode': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.publishermobileapp': {
            'Meta': {'object_name': 'PublisherMobileApp'},
            'age': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'appcategories': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'applicationname': ('django.db.models.fields.TextField', [], {'db_index': 'True'}),
            'appstoreurl': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ethnicity': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'gendertarget': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'income': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'marketplaceurl': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'playstoreurl': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'publisherid': ('django.db.models.fields.TextField', [], {'db_index': 'True'})
        },
        u'spendata.publisherwebapp': {
            'Meta': {'object_name': 'PublisherWebApp'},
            'age': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'categoryfilters': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ethnicity': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'gendertargetting': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'income': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'publisherid': ('django.db.models.fields.TextField', [], {'db_index': 'True'}),
            'websitename': ('django.db.models.fields.TextField', [], {'db_index': 'True'}),
            'websiteurl': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'})
        },
        u'spendata.userfavoritedeals': {
            'Meta': {'object_name': 'UserFavoriteDeals'},
            'advertiser_id': ('django.db.models.fields.IntegerField', [], {}),
            'advertiser_name': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user_id': ('django.db.models.fields.TextField', [], {'db_index': 'True'})
        }
    }

    complete_apps = ['spendata']